### ISSUE TITLE
Parsing not working with Clueweb12

### ISSUE THREAD

**Issue by amallia** [pisa-engine/pisa#62]
```
WARC/1.0
WARC-Type: response
WARC-Date: 2012-02-10T21:51:20Z
WARC-TREC-ID: clueweb12-0000tw-00-00013
WARC-Target-URI: http://cheapcosthealthinsurance.com/2012/01/25/what-is-hiv-aids/
WARC-Payload-Digest: sha1:YZUOJNSUMFG3JVUKM6LBHMRMMHWLVNQ4
WARC-IP-Address: 100.42.59.15
WARC-Record-ID: <urn:uuid:74edc71e-a881-4942-81fc-a40db4bf1fb9>
Content-Type: application/http; msgtype=response
Content-Length: 71726

HTTP/1.1 200 OK
Date: Fri, 10 Feb 2012 21:51:22 GMT
Server: Apache/2.2.21 (Unix) mod_ssl/2.2.21 OpenSSL/0.9.8e-fips-rhel5 mod_auth_passthrough/2.1 mod_bwlimited/1.4 FrontPage/5.0.2.2635 mod_jk/1.2.32
X-Powered-By: PHP/5.2.17
X-Pingback: http://cheapcosthealthinsurance.com/xmlrpc.php
Link: <http://cheapcosthealthinsurance.com/?p=711>; rel=shortlink
Connection: close
Content-Type: text/html; charset=UTF-8
```

**Comment by amallia** [comment]
Should be solved once we integrate these changes: https://github.com/pisa-engine/warcpp/pull/3

**Comment by elshize** [comment]
We still get a segfault, probably for a different reason.

Run on `etna`:
```
find ../collections/ClueWeb12B -type f | sort | xargs zcat | ~/pisa/build/bin/parse_collection -o Clueweb12B-warc-gumbo-porter2/cw12b -j 8 -f warc --stemmer porter2 --content-parser html
```

It most likely occurred in batch 275, or one of 280-288.

**Comment by amallia** [comment]
Fixed :)
